### ISSUE TITLE
[v1] `loadOnce()` as the single directive

### ISSUE THREAD

**Issue by tabacitu** [DigitallyHappy/assets#6]
Pedro said - what if we only have:

```php

// if there's a file extension... it's a file
// (alternatively, if it has dots or slashes... it's a path or URL)
@loadOnce('path/to/js.js')
@loadOnce('path/to/css.css')

// if it doesn't have an extension... it's a block
@loadOnce('unique_name_for_code_block')
    <script>
        <!-- Your JS here -->
    </script>

    <!-- OR -->

    <style>
        <!-- Your CSS here -->
    </style>
@endLoadOnce
```

**Comment by promatik** [comment]
This looks promising!

I think we should not rely on dots or slashes, because a path may be just `@loadOnce('main.js')`, we should rely on the name ending with `.js` or `.css`, and expect users to not use ids that look like a file name.

Maybe we could also check if file exists, but it's more "expensive" probably and in a situation where the file mistakenly doesn't exist it would be, wrongly, expect an ending block – so it's not a good idea.
